const pool = require("../config/db");
const nodemailer = require("nodemailer");

// Normalize reportTypes into a clean JS array
function normalizeReportTypes(input) {
  if (!input) return [];
  if (Array.isArray(input)) return input;

  if (typeof input === "string") {
    try {
      const parsed = JSON.parse(input);
      if (Array.isArray(parsed)) return parsed;
    } catch (e) {}
  }

  return [input];
}

// =========================
// CREATE NEAR MISS
// =========================
exports.createNearMiss = async (req, res) => {
  console.log("REQ BODY:", req.body);

  try {
    const {
      department,
      location,
      date,
      additionalTeam,
      description,
      actionsTaken,
      suggestion,
      followup,
      status,
      observer_id,
      observer_name
    } = req.body;

    const reportTypesRaw = req.body.reportTypes;
    const normalizedTypes = normalizeReportTypes(reportTypesRaw);

    // New photo system
    const photoPath = req.file ? req.file.filename : null;

    // Lookup leader
    const leaderResult = await pool.query(
      `SELECT leader_id FROM employees WHERE employee_id = $1`,
      [observer_id]
    );
    const leaderId = leaderResult.rows[0]?.leader_id || null;

    // Lookup shift
    const shiftResult = await pool.query(
      `SELECT shift FROM employees WHERE employee_id = $1`,
      [observer_id]
    );
    const employeeShift = shiftResult.rows[0]?.shift || null;

    // Insert record
    const result = await pool.query(
      `INSERT INTO nearmiss_reports 
      (observer_id, observer_name, department, location, date, shift,
       additional_team, report_types, description, actions_taken, suggestion,
       followup, status, leader_id, photo_path)
      VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)
      RETURNING *`,
      [
        observer_id,
        observer_name,
        department,
        location,
        date,
        employeeShift,
        additionalTeam,
        JSON.stringify(normalizedTypes),
        description,
        actionsTaken,
        suggestion,
        followup,
        status || "Open",
        leaderId,
        photoPath
      ]
    );

    const saved = result.rows[0];

    // =========================
    // FOLLOW-UP EMAIL
    // =========================
    if (followup === "yes") {
      try {
        let leaderEmail = null;

        if (leaderId) {
          const leaderEmailResult = await pool.query(
            `SELECT email FROM employees WHERE employee_id = $1`,
            [leaderId]
          );
          leaderEmail = leaderEmailResult.rows[0]?.email || null;
        }

        const safetyResult = await pool.query(
          `SELECT email FROM employees WHERE employee_id IN ('103118','245177','123850')`
        );
        const safetyEmails = safetyResult.rows.map(r => r.email);

        const recipients = [leaderEmail, ...safetyEmails].filter(Boolean);

        const transporter = nodemailer.createTransport({
          host: "smtp.gmail.com",
          port: 587,
          secure: false,
          auth: {
            user: process.env.SMTP_USER,
            pass: process.env.SMTP_PASS
          }
        });

        await transporter.sendMail({
          from: process.env.SMTP_USER,
          to: recipients,
          subject: "Near Miss Follow-Up Requested",
          html: `
            <h2>Near Miss Follow-Up Requested</h2>

            <p><strong>Observer:</strong> ${observer_name} (${observer_id})</p>
            <p><strong>Department:</strong> ${department}</p>
            <p><strong>Location:</strong> ${location}</p>
            <p><strong>Date:</strong> ${date}</p>
            <p><strong>Report Types:</strong> ${normalizedTypes.join(", ")}</p>

            <p><strong>Description:</strong> ${description}</p>
            <p><strong>Immediate Actions:</strong> ${actionsTaken}</p>
            <p><strong>Suggested Corrective Action:</strong> ${suggestion}</p>
            <p><strong>Additional Team:</strong> ${additionalTeam}</p>

            <p><strong>Follow-Up Requested:</strong> YES</p>

            <hr/>
            <p>This message was automatically generated by the Safety App.</p>
          `
        });

      } catch (emailErr) {
        console.error("Near Miss follow-up email failed:", emailErr);
      }
    }

    res.json(saved);

  } catch (err) {
    console.error("Create Near Miss Error:", err);
    res.status(500).json({ error: "Failed to create Near Miss report" });
  }
};
