const pool = require("../config/db");
const nodemailer = require("nodemailer");

// Normalize reportTypes into a clean JS array
function normalizeReportTypes(input) {
  if (!input) return [];
  if (Array.isArray(input)) return input;

  if (typeof input === "string") {
    try {
      const parsed = JSON.parse(input);
      if (Array.isArray(parsed)) return parsed;
    } catch (e) {}
  }

  return [input];
}

// CREATE
exports.createNearMiss = async (req, res) => {
  console.log("REQ BODY:", req.body);

  try {
    const department = req.body.department;
    const location = req.body.location;
    const date = req.body.date;
    const additionalTeam = req.body.additionalTeam;
    const description = req.body.description;
    const actionsTaken = req.body.actionsTaken;
    const suggestion = req.body.suggestion;
    const followup = req.body.followup;
    const status = req.body.status;

    // Logged‑in submitter
    const observerId = req.body.observer_id;
    const observerName = req.body.observer_name;

    const reportTypesRaw = req.body.reportTypes;
    const normalizedTypes = normalizeReportTypes(reportTypesRaw);

    const photoPath = req.file ? req.file.filename : null;

    // Lookup leader of the observer
    const leaderResult = await pool.query(
      `SELECT leader_id FROM employees WHERE employee_id = $1`,
      [observerId]
    );
    const leaderId = leaderResult.rows[0]?.leader_id || null;

    // Lookup shift from employees table
    const shiftResult = await pool.query(
      `SELECT shift FROM employees WHERE employee_id = $1`,
      [observerId]
    );
    const employeeShift = shiftResult.rows[0]?.shift || null;

    // Insert record (stores observer_id, observer_name, correct shift, correct leader_id)
    const result = await pool.query(
      `INSERT INTO nearmiss_reports 
      (observer_id, observer_name, department, location, date, shift,
       additional_team, report_types, description, actions_taken, suggestion,
       followup, status, leader_id, photo_path)
      VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)
      RETURNING *`,
      [
        observerId,
        observerName,
        department,
        location,
        date,
        employeeShift,
        additionalTeam,
        JSON.stringify(normalizedTypes),
        description,
        actionsTaken,
        suggestion,
        followup,
        status || "Open",
        leaderId,
        photoPath,
      ]
    );

    const saved = result.rows[0];

    // FOLLOW-UP EMAIL LOGIC
    if (followup === "yes") {
      try {
        // Lookup leader email
        let leaderEmail = null;
        if (leaderId) {
          const leaderEmailResult = await pool.query(
            `SELECT email FROM employees WHERE employee_id = $1`,
            [leaderId]
          );
          leaderEmail = leaderEmailResult.rows[0]?.email || null;
        }

        // Safety team
        const safetyResult = await pool.query(
          `SELECT email FROM employees WHERE employee_id IN ('103118','245177','123850')`
        );
        const safetyEmails = safetyResult.rows.map(r => r.email);

        const recipients = [leaderEmail, ...safetyEmails].filter(Boolean);

        const transporter = nodemailer.createTransport({
          host: "smtp.office365.com",
          port: 587,
          secure: false,
          auth: {
            user: process.env.SMTP_USER,
            pass: process.env.SMTP_PASS
          }
        });

        await transporter.sendMail({
          from: process.env.SMTP_USER,
          to: recipients,
          subject: "Near Miss Follow-Up Requested",
          html: `
            <h2>Near Miss Follow-Up Requested</h2>

            <p><strong>Observer:</strong> ${observerName} (${observerId})</p>
            <p><strong>Department:</strong> ${department}</p>
            <p><strong>Location:</strong> ${location}</p>
            <p><strong>Date:</strong> ${date}</p>
            <p><strong>Report Types:</strong> ${normalizedTypes.join(", ")}</p>

            <p><strong>Description:</strong> ${description}</p>
            <p><strong>Immediate Actions:</strong> ${actionsTaken}</p>
            <p><strong>Suggested Corrective Action:</strong> ${suggestion}</p>
            <p><strong>Additional Team:</strong> ${additionalTeam}</p>

            <p><strong>Follow-Up Requested:</strong> YES</p>

            <hr/>
            <p>This message was automatically generated by the Safety App.</p>
          `
        });

      } catch (emailErr) {
        console.error("Near Miss follow-up email failed:", emailErr);
      }
    }

    res.json(saved);

  } catch (err) {
    console.error("Create Near Miss Error:", err);
    res.status(500).json({ error: "Failed to create Near Miss report" });
  }
};

// GET ALL
exports.getAllNearMiss = async (req, res) => {
  try {
    const result = await pool.query(
      "SELECT * FROM nearmiss_reports ORDER BY id DESC"
    );
    res.json(result.rows);
  } catch (err) {
    console.error("Get All Near Miss Error:", JSON.stringify(err));
    res.status(500).json({ error: "Failed to fetch reports" });
  }
};

// GET ONE
exports.getNearMissById = async (req, res) => {
  try {
    const result = await pool.query(
      "SELECT * FROM nearmiss_reports WHERE id = $1",
      [req.params.id]
    );

    if (result.rows.length === 0) {
      return res.status(404).json({ error: "Not found" });
    }

    res.json(result.rows[0]);
  } catch (err) {
    console.error("Get Near Miss Error:", err);
    res.status(500).json({ error: "Failed to fetch report" });
  }
};

// UPDATE
exports.updateNearMiss = async (req, res) => {
  try {
    const id = req.params.id;

    const department = req.body.department;
    const location = req.body.location;
    const date = req.body.date;
    const additionalTeam = req.body.additionalTeam;
    const description = req.body.description;
    const actionsTaken = req.body.actionsTaken;
    const suggestion = req.body.suggestion;
    const followup = req.body.followup;
    const status = req.body.status;
    const shift = req.body.shift;

    const reportTypesRaw = req.body.reportTypes;
    const normalizedTypes = normalizeReportTypes(reportTypesRaw);

    const photoPath = req.file ? req.file.filename : null;

    const result = await pool.query(
      `UPDATE nearmiss_reports SET
        department = $1,
        location = $2,
        date = $3,
        additional_team = $4,
        report_types = $5,
        description = $6,
        actions_taken = $7,
        suggestion = $8,
        followup = $9,
        status = $10,
        shift = $11,
        photo_path = COALESCE($12, photo_path),
        updated_at = NOW()
      WHERE id = $13
      RETURNING *`,
      [
        department,
        location,
        date,
        additionalTeam,
        JSON.stringify(normalizedTypes),
        description,
        actionsTaken,
        suggestion,
        followup,
        status,
        shift,
        photoPath,
        id,
      ]
    );

    res.json(result.rows[0]);
  } catch (err) {
    console.error("Update Near Miss Error:", err);
    res.status(500).json({ error: "Failed to update report" });
  }
};

// DELETE
exports.deleteNearMiss = async (req, res) => {
  try {
    await pool.query("DELETE FROM nearmiss_reports WHERE id = $1", [
      req.params.id,
    ]);
    res.json({ success: true });
  } catch (err) {
    console.error("Delete Near Miss Error:", err);
    res.status(500).json({ error: "Failed to delete report" });
  }
};