const express = require("express");
const router = express.Router();
const path = require("path");
const fs = require("fs");
const PDFDocument = require("pdfkit");

// ⭐ USE YOUR EXISTING GLOBAL UPLOAD MIDDLEWARE
const { uploadPhotos } = require("../../middleware/upload");

// ⭐ PERSISTENT DISK PATHS
const PDF_DIR = "/data/documents/rack-inspection";

// Ensure PDF directory exists
if (!fs.existsSync(PDF_DIR)) {
  fs.mkdirSync(PDF_DIR, { recursive: true });
}

// ─── Question + value maps for clean PDF output ──────────────────────────────
const QUESTION_MAP = {
  uprightsDamage:   "Damage to uprights or columns?",
  beamsDamage:      "Damage to beams or cross-members?",
  lockingPins:      "Missing or damaged safety locking pins?",
  beamDeflection:   "Beam deflection or sagging?",
  deckingCondition: "Damaged or missing decking?",
  rustCorrosion:    "Rust, corrosion, or metal fatigue?",
  impactDamage:     "Evidence of forklift impact?",
  rackFeet:         "If present, are Rack Feet in good condition?",
  anchorsSecure:    "Anchors and base plates secure?",
  plumbFrontBack:   "Rack vertical front-to-back? (standing straight, no forward/backward lean)",
  plumbLeftRight:   "Rack vertical left-to-right? (standing straight, no side lean)",
  leaning:          "Any leaning or instability?",
  overloaded:       "Any signs of overloading?",
  palletCondition:  "Pallets in good condition?",
  labelsVisible:    "Load capacity labels visible?",
  aislesClear:      "Aisles clear and unobstructed?",
  sprinklerClearance:"Proper clearance from sprinklers?",
  fireExitClear:    "Fire exits and extinguishers clear?",
};

const VALUE_MAP = {
  yes: "Good",
  no:  "Issue",
  na:  "Not Applicable",
};

// ─── Footer helper (logo on every page, split footer, page numbers) ───────────
function addFooter(doc) {
  const footerY = doc.page.height - 40;

  // Left side footer
  doc.fontSize(9)
     .fillColor("#555555")
     .text("Generated by Dal‑Tile Safety App — Muskogee Operations", 40, footerY, {
       align: "left"
     });

  // Right side page number
  doc.fontSize(9)
     .fillColor("#555555")
     .text(`Page ${doc.page.number}`, -40, footerY, {
       align: "right"
     });
}

// ─── Add logo to every page ───────────────────────────────────────────────────
function addLogo(doc) {
  try {
    doc.image(
      path.join(__dirname, "..", "..", "public", "logo.jpg"),
      40,
      20,
      { width: 70 }
    );
  } catch (e) {
    console.log("Logo not found on this page.");
  }
}

// ─── POST /api/forms/rack-inspection ─────────────────────────────────────────
router.post("/", uploadPhotos.single("photo"), async (req, res) => {
  try {
    const {
      rackId,
      notes,
      submitter,
      ...fields
    } = req.body;

    // ⭐ Pull employee_id from headers (REAL FK)
    const employeeId = req.headers["employee_id"];
    const submittedBy = submitter || "Unknown";

    if (!employeeId) {
      return res.status(400).json({
        success: false,
        error: "Missing employee_id header."
      });
    }

    // ⭐ Photo saved to persistent disk automatically:
    const photoPath = req.file ? req.file.path : null;

    // ⭐ PDF path on persistent disk
    const pdfPath = path.join(
      PDF_DIR,
      `RackInspection_${rackId}_${Date.now()}.pdf`
    );

    // ─── Generate PDF ─────────────────────────────────────────────────────────
    const doc = new PDFDocument({ margin: 40 });
    const stream = fs.createWriteStream(pdfPath);
    doc.pipe(stream);

    // ===== HEADER BAR =====
    doc.rect(0, 0, doc.page.width, 90).fill("#B30000");

    addLogo(doc);

    doc.fillColor("#FFFFFF")
       .fontSize(22)
       .font("Helvetica-Bold")
       .text("Dal‑Tile Muskogee Rack Inspection Report", 130, 30, {
         align: "left"
       });

    doc.fillColor("#000000");

    // ===== METADATA BLOCK =====
    doc.moveDown(3);
    doc.rect(40, 110, doc.page.width - 80, 120).fill("#F2F2F2");

    doc.fillColor("#000000")
       .fontSize(12)
       .font("Helvetica-Bold")
       .text("Rack ID:", 55, 125)
       .font("Helvetica")
       .text(rackId, 200, 125);

    doc.font("Helvetica-Bold")
       .text("Submitted By:", 55, 145)
       .font("Helvetica")
       .text(submittedBy, 200, 145);

    doc.font("Helvetica-Bold")
       .text("Employee ID:", 55, 165)
       .font("Helvetica")
       .text(employeeId, 200, 165);

    doc.font("Helvetica-Bold")
       .text("Submission Date:", 55, 185)
       .font("Helvetica")
       .text(
         new Date().toLocaleString("en-US", { timeZone: "America/Chicago" }),
         200,
         185
       );

    addFooter(doc);

    // ===== SECTION HEADER: INSPECTION DETAILS =====
    doc.addPage();
    addLogo(doc);

    doc.rect(0, 0, doc.page.width, 90).fill("#B30000");
    doc.fillColor("#FFFFFF")
       .fontSize(22)
       .font("Helvetica-Bold")
       .text("Inspection Details", 40, 30);

    doc.fillColor("#000000").moveDown(4);

    // ===== FORM FIELDS =====
    Object.entries(fields).forEach(([key, rawValue]) => {
      const question = QUESTION_MAP[key] || key;
      const mappedValue = VALUE_MAP[rawValue] || rawValue || "None";

      doc.font("Helvetica-Bold").fontSize(12).text(question + ":");
      doc.font("Helvetica").fontSize(11).text(mappedValue);
      doc.moveDown(1);
    });

    addFooter(doc);

    // ===== NOTES SECTION =====
    doc.addPage();
    addLogo(doc);

    doc.rect(0, 0, doc.page.width, 90).fill("#B30000");
    doc.fillColor("#FFFFFF")
       .fontSize(22)
       .font("Helvetica-Bold")
       .text("Notes", 40, 30);

    doc.fillColor("#000000").moveDown(4);
    doc.font("Helvetica").fontSize(12).text(notes || "None");

    addFooter(doc);

    // ===== PHOTO PAGE =====
    if (photoPath) {
      doc.addPage();
      addLogo(doc);

      doc.rect(0, 0, doc.page.width, 90).fill("#B30000");
      doc.fillColor("#FFFFFF")
         .fontSize(22)
         .font("Helvetica-Bold")
         .text("Attached Photo", 40, 30);

      doc.fillColor("#000000").moveDown(4);

      try {
        doc.image(photoPath, {
          fit: [450, 450],
          align: "center",
          valign: "center"
        });
      } catch (err) {
        doc.text("Photo could not be rendered.");
      }

      addFooter(doc);
    }

    doc.end();

    // ─── When PDF is finished writing ─────────────────────────────
    stream.on("finish", async () => {
      const pool = require("../../config/db");

      // 1️⃣ Insert into documents table
      const docResult = await pool.query(
        `INSERT INTO documents (folder_id, title, description, created_by, created_at, is_active)
         VALUES ($1, $2, $3, $4, NOW(), true)
         RETURNING id`,
        [
          19,
          `Rack Inspection - ${rackId}`,
          notes || "",
          employeeId
        ]
      );

      const documentId = docResult.rows[0].id;

      // 2️⃣ Insert into document_versions table
      await pool.query(
        `INSERT INTO document_versions (document_id, version_number, file_path, file_type, uploaded_by, uploaded_at, change_comment)
         VALUES ($1, $2, $3, $4, $5, NOW(), $6)`,
        [
          documentId,
          1,
          pdfPath,
          "application/pdf",
          employeeId,
          "Initial upload"
        ]
      );

      return res.json({
        success: true,
        message: "Rack inspection submitted.",
        pdfPath,
        photoPath,
      });
    });

  } catch (err) {
    console.error("Rack Inspection Error:", err);
    res.status(500).json({ success: false, error: "Server error." });
  }
});

module.exports = router;
