const express = require("express");
const router = express.Router();
const path = require("path");
const fs = require("fs");
const PDFDocument = require("pdfkit");

// ⭐ USE YOUR EXISTING GLOBAL UPLOAD MIDDLEWARE
const { uploadPhotos } = require("../../middleware/upload");

// ⭐ PERSISTENT DISK PATHS
const PDF_DIR = "/data/documents/rack-inspection";

// Ensure PDF directory exists
if (!fs.existsSync(PDF_DIR)) {
  fs.mkdirSync(PDF_DIR, { recursive: true });
}

// ─── POST /api/forms/rack-inspection ───────────────────────────────
router.post("/", uploadPhotos.single("photo"), async (req, res) => {
  try {
    const {
      rackId,
      notes,
      submitter,
      ...fields
    } = req.body;

    // ⭐ Pull employee_id from headers (REAL FK)
    const employeeId = req.headers["employee_id"];

    if (!employeeId) {
      return res.status(400).json({
        success: false,
        error: "Missing employee_id header."
      });
    }

    // ⭐ Photo saved to persistent disk automatically:
    const photoPath = req.file ? req.file.path : null;

    // ⭐ PDF path on persistent disk
    const pdfPath = path.join(
      PDF_DIR,
      `RackInspection_${rackId}_${Date.now()}.pdf`
    );

// ─── Generate PDF (Professional Dal‑Tile Format) ─────────────────────────────
const doc = new PDFDocument({
  margin: 40
});
const stream = fs.createWriteStream(pdfPath);
doc.pipe(stream);

// ===== HEADER BAR =====
doc.rect(0, 0, doc.page.width, 90)
   .fill("#B30000");

try {
  doc.image(path.join(__dirname, "../../public/logo.jpg"), 40, 20, { width: 70 });
} catch (e) {
  console.log("Logo not found, skipping logo render.");
}

doc.fillColor("#FFFFFF")
   .fontSize(22)
   .font("Helvetica-Bold")
   .text("Dal‑Tile Muskogee Rack Inspection Report", 130, 30, {
     align: "left"
   });

// Reset fill for body
doc.fillColor("#000000");

// ===== METADATA BLOCK =====
doc.moveDown(3);
doc.rect(40, 110, doc.page.width - 80, 120)
   .fill("#F2F2F2");

doc.fillColor("#000000")
   .fontSize(12)
   .font("Helvetica-Bold")
   .text("Rack ID:", 55, 125)
   .font("Helvetica")
   .text(rackId, 200, 125);

doc.font("Helvetica-Bold")
   .text("Submitted By:", 55, 145)
   .font("Helvetica")
   .text(submitter, 200, 145);

doc.font("Helvetica-Bold")
   .text("Employee ID:", 55, 165)
   .font("Helvetica")
   .text(employeeId, 200, 165);

doc.font("Helvetica-Bold")
   .text("Submission Date:", 55, 185)
   .font("Helvetica")
   .text(new Date().toLocaleString(), 200, 185);

// ===== SECTION HEADER =====
doc.moveDown(6);
doc.rect(40, doc.y, doc.page.width - 80, 30)
   .fill("#B30000");

doc.fillColor("#FFFFFF")
   .font("Helvetica-Bold")
   .fontSize(14)
   .text("Inspection Details", 55, doc.y - 22);

doc.fillColor("#000000")
   .moveDown(2);

// ===== FORM FIELDS =====
Object.entries(fields).forEach(([key, value]) => {
  doc.font("Helvetica-Bold")
     .fontSize(12)
     .text(key.replace(/_/g, " ") + ":");

  doc.font("Helvetica")
     .fontSize(11)
     .text(value || "None");

  doc.moveDown(1);
});

// ===== NOTES SECTION =====
doc.moveDown(1.5);
doc.rect(40, doc.y, doc.page.width - 80, 30)
   .fill("#B30000");

doc.fillColor("#FFFFFF")
   .font("Helvetica-Bold")
   .fontSize(14)
   .text("Notes", 55, doc.y - 22);

doc.fillColor("#000000")
   .moveDown(2)
   .font("Helvetica")
   .fontSize(11)
   .text(notes || "None");

// ===== PHOTO PAGE =====
if (photoPath) {
  doc.addPage();

  doc.font("Helvetica-Bold")
     .fontSize(16)
     .text("Attached Photo", { align: "center" });

  doc.moveDown();

  try {
    doc.image(photoPath, {
      fit: [450, 450],
      align: "center",
      valign: "center"
    });
  } catch (err) {
    doc.text("Photo could not be rendered.");
  }
}

// ===== FOOTER =====
doc.moveTo(40, doc.page.height - 50)
   .lineTo(doc.page.width - 40, doc.page.height - 50)
   .strokeColor("#CCCCCC")
   .stroke();

doc.fontSize(9)
   .fillColor("#555555")
   .text("Generated by Dal‑Tile Safety App — Muskogee Operations", 40, doc.page.height - 40, {
     align: "center"
   });

doc.end();

    // ─── When PDF is finished writing ─────────────────────────────
    stream.on("finish", async () => {

      const pool = require("../../config/db");

      // 1️⃣ Insert into documents table
      const docResult = await pool.query(
        `INSERT INTO documents (folder_id, title, description, created_by, created_at, is_active)
         VALUES ($1, $2, $3, $4, NOW(), true)
         RETURNING id`,
        [
          19, // Rack Inspections folder
          `Rack Inspection - ${rackId}`,
          notes || "",
          employeeId   // ⭐ MUST be a valid FK
        ]
      );

      const documentId = docResult.rows[0].id;

      // 2️⃣ Insert into document_versions table
      await pool.query(
        `INSERT INTO document_versions (document_id, version_number, file_path, file_type, uploaded_by, uploaded_at, change_comment)
         VALUES ($1, $2, $3, $4, $5, NOW(), $6)`,
        [
          documentId,
          1,
          pdfPath,
          "application/pdf",
          employeeId,   // ⭐ MUST be a valid FK
          "Initial upload"
        ]
      );

      // ⭐ Final response
      return res.json({
        success: true,
        message: "Rack inspection submitted.",
        pdfPath,
        photoPath,
      });
    });

  } catch (err) {
    console.error("Rack Inspection Error:", err);
    res.status(500).json({ success: false, error: "Server error." });
  }
});

module.exports = router;
